import { fetchData } from "../api/data.api";
import { MotorcycleData } from "../types/motorcycle-data";
import useExportJson from "./useExportJson";

export const useLoadDataFromApi = () => {
  const [exportJson] = useExportJson();
  const makes: string[] = [
    "Access",
    "Adly",
    "Aeon",
    "American IronHorse",
    "Aprilia",
    "Arctic",
    "Bajaj",
    "Baotian",
    "Barossa",
    "Beeline",
    "Benelli",
    "Beta",
    "Big dog",
    "Bimota",
    "Blata",
    "BMW",
    "Boom Trikes",
    "Boss Hoss",
    "Brixton",
    "Brough Superior",
    "BSA Motors",
    "Buell",
    "Cagiva",
    "California",
    "Can-Am",
    "Cectek",
    "CF Moto",
    "Cobra",
    "CPI",
    "CSC Motorcycles",
    "Daelim",
    "Derbi",
    "Dinli",
    "DKW",
    "Ducati",
    "E-max",
    "E-Ton",
    "emco",
    "Energica",
    "Excelsior",
    "Fantic",
    "FB Mondial",
    "Gas Gas",
    "Generic",
    "Gilera",
    "Goes",
    "Govecs",
    "Harley-Davidson",
    "Hercules",
    "Hero",
    "Honda",
    "Horex",
    "Horwin",
    "Husaberg",
    "Husqvarna",
    "Hyosung",
    "Ice Bear",
    "Indian",
    "Italjet",
    "Jawa",
    "Johnny Pag",
    "Kayo",
    "Kawasaki",
    "Keeway",
    "Kreidler",
    "KSR",
    "KTM",
    "Kumpan",
    "Kymco",
    "Lambretta",
    "Laverda",
    "Lehman",
    "Lifan",
    "Linhai",
    "LML",
    "Luxxon",
    "Maico",
    "Malaguti",
    "Mash",
    "MBK",
    "Megelli",
    "Mission",
    "Motobi",
    "Moto Guzzi",
    "Moto Morini",
    "Motowell",
    "MV Agusta",
    "MZ",
    "Niu",
    "Norton",
    "NSU",
    "Peugeot",
    "PGO",
    "Piaggio",
    "Polaris",
    "Precision Cycle Works",
    "Puch",
    "QJmotor",
    "Quadro",
    "Raybar",
    "Rewaco",
    "Rieju",
    "Royal",
    "Sachs",
    "Seat",
    "Sherco",
    "Shineray",
    "Silence",
    "Simson",
    "Skyteam",
    "Stels",
    "Super Soco",
    "Suzuki",
    "SWM",
    "Sym",
    "Tank Sports",
    "Tauris",
    "TGB",
    "TM Racing",
    "Triton",
    "Triumph",
    "TRS",
    "Ural",
    "Vespa",
    "Victory",
    "Voge",
    "Voxan",
    "Yamaha",
    "Zero",
    "Zongshen",
    "Zontes",
    "Zündapp",
  ];

  const loadData = async () => {
    let data: MotorcycleData[] = [];
    for (let index = 0; index < makes.length; index++) {
      let offset = 0;
      let pageData: MotorcycleData[] = [];

      do {
        pageData = await fetchData(makes[index], offset);
        offset += 30;
        data = data.concat(pageData);
      } while (pageData.length === 30);
    }

    exportJson(JSON.stringify(data));
  };

  return [loadData];
};

export default useLoadDataFromApi;
